#!/bin/sh

if [ -d "/etc/X11/xinit/xinitrc.d" ]
then
  for f in /etc/X11/xinit/xinitrc.d/*;
  do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# preferences
[ -f "$HOME/.Xresources" ] && xrdb ~/.Xresources
xset s off
xset -dpms
xset s noblank

# xsession.target
if [ "$(ps -p 1 -o comm=)" = "systemd" ] && [ -n "$(command -vp systemctl)" ]
then
  systemctl --user import-environment PATH DBUS_SESSION_BUS_ADDRESS
  systemctl --no-block --user start xsession.target
fi

# xmonad
if [ -n "$(command -vp xmonad)" ]
then
  xmonad
fi
