#!/bin/sh

if [ -d "/etc/X11/xinit/xinitrc.d" ]
then
  for f in /etc/X11/xinit/xinitrc.d/*;
  do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -n "$(command -vp xmonad)" ]
then

  # X preferences
  [ -f "$HOME/.Xresources" ] && xrdb ~/.Xresources
  xset s off
  xset -dpms
  xset s noblank

  # xmonad
  ~/.xmonad/autostart.sh
  xmonad
fi
